export type ScressFigures =
  | 'Turm'
  | 'Pferd'
  | 'Läufer'
  | 'Königin'
  | 'König'
  | 'Bauer'
  | ''
  | 'Bauer-W'
  | 'Turm-W'
  | 'Pferd-W'
  | 'Läufer-W'
  | 'Königin-W'
  | 'König-W'

export type FigureSituation = 'ENEMY' | 'FRIEND'
